interface DokployBase {
  baseUrl: string;
  token: string;
}

export type { DokployBase };

async function dokployPost<T>(url: string, token: string, body: unknown): Promise<T> {
  const res = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": token,
    },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error(`Dokploy API error ${res.status}: ${text}`);
  }
  return res.json() as Promise<T>;
}

async function dokployGet<T>(url: string, token: string): Promise<T> {
  const res = await fetch(url, {
    headers: { "x-api-key": token },
  });
  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error(`Dokploy API error ${res.status}: ${text}`);
  }
  return res.json() as Promise<T>;
}

interface CreateProjectResponse {
  project: { projectId: string };
  environment: { environmentId: string };
}

export async function createDokployProject(
  params: DokployBase & { name: string }
): Promise<{ projectId: string; environmentId: string }> {
  const data = await dokployPost<CreateProjectResponse>(
    `${params.baseUrl}/api/project.create`,
    params.token,
    { name: params.name, description: "Generated by Agentic Builder" }
  );
  return {
    projectId: data.project.projectId,
    environmentId: data.environment.environmentId,
  };
}

interface ProjectSummary {
  projectId: string;
  name: string;
  environments?: Array<{ environmentId: string; name?: string }>;
}

/** List all projects visible to the API token. */
export async function listDokployProjects(
  params: DokployBase,
): Promise<ProjectSummary[]> {
  return dokployGet<ProjectSummary[]>(
    `${params.baseUrl}/api/project.all`,
    params.token,
  );
}

/** Look up one project (includes environments) by id. */
export async function getDokployProject(
  params: DokployBase & { projectId: string },
): Promise<ProjectSummary> {
  return dokployGet<ProjectSummary>(
    `${params.baseUrl}/api/project.one?projectId=${encodeURIComponent(params.projectId)}`,
    params.token,
  );
}

export async function createDokployCompose(
  params: DokployBase & { name: string; projectId: string; environmentId: string }
): Promise<{ composeId: string; appName: string }> {
  const data = await dokployPost<{ composeId: string; appName: string }>(
    `${params.baseUrl}/api/compose.create`,
    params.token,
    { name: params.name, projectId: params.projectId, environmentId: params.environmentId }
  );
  return { composeId: data.composeId, appName: data.appName };
}

/**
 * Look up an existing compose by id. Returns `null` when Dokploy says it
 * doesn't exist (404 / NOT_FOUND), which is the legitimate "saved compose
 * is stale, recreate it" branch in the deploy pipeline. Other errors
 * (5xx, network) still throw so we don't silently lose a real Dokploy
 * outage.
 */
export async function getDokployCompose(
  params: DokployBase & { composeId: string },
): Promise<{ composeId: string; appName: string } | null> {
  const url = `${params.baseUrl}/api/compose.one?composeId=${encodeURIComponent(params.composeId)}`;
  const res = await fetch(url, { headers: { "x-api-key": params.token } });
  if (res.status === 404) return null;
  if (!res.ok) {
    const text = await res.text().catch(() => "");
    // Dokploy returns 200 with a NOT_FOUND code in body for some endpoints —
    // treat that as missing too.
    if (/NOT_FOUND/i.test(text)) return null;
    throw new Error(`Dokploy compose.one error ${res.status}: ${text}`);
  }
  const data = (await res.json()) as {
    composeId?: string;
    appName?: string;
    code?: string;
  };
  if (data.code === "NOT_FOUND" || !data.composeId) return null;
  return { composeId: data.composeId, appName: data.appName ?? "" };
}

export async function createDokployDomain(
  params: DokployBase & { composeId: string; host: string; serviceName: string }
): Promise<void> {
  await dokployPost(
    `${params.baseUrl}/api/domain.create`,
    params.token,
    {
      composeId: params.composeId,
      host: params.host,
      port: 80,
      serviceName: params.serviceName,
      certificateType: "none",
    }
  );
}

export async function updateDokployCompose(
  params: DokployBase & {
    composeId: string;
    repository: string;
    branch: string;
    env: string;
    /** When set, Dokploy clones via SSH using this stored key (private repos). */
    sshKeyId?: string;
  }
): Promise<void> {
  const body: Record<string, unknown> = {
    composeId: params.composeId,
    sourceType: "git",
    customGitUrl: params.repository,
    customGitBranch: params.branch,
    composeType: "docker-compose",
    env: params.env,
  };
  if (params.sshKeyId) body.customGitSSHKeyId = params.sshKeyId;
  // Redact any embedded credential before logging the request.
  console.log(
    "[dokploy] compose.update request:",
    JSON.stringify({ ...body, env: "<redacted>" }),
  );
  const res = await dokployPost<unknown>(`${params.baseUrl}/api/compose.update`, params.token, body);
  console.log("[dokploy] compose.update response:", JSON.stringify(res));
}

export async function deployDokployCompose(
  params: DokployBase & { composeId: string }
): Promise<void> {
  await dokployPost(
    `${params.baseUrl}/api/compose.deploy`,
    params.token,
    { composeId: params.composeId }
  );
}

// ── Redis service API ───────────────────────────────────────────────────────
// Dokploy treats Redis as a first-class managed Service. One container per call;
// Dokploy puts it on `dokploy-network` and (when externalPort is set) publishes
// the host port so it's reachable from outside the Docker network.

export interface CreateRedisResponse {
  redisId: string;
  appName: string;
}

/**
 * Create a managed Redis service inside an existing Dokploy project/environment.
 * Pass `externalPort` to publish the host port (required for local dev access
 * without docker). Random by default; caller can pick a deterministic port if
 * they want per-project stable addresses.
 */
export async function createDokployRedis(
  params: DokployBase & {
    name: string;
    appName: string;
    projectId: string;
    environmentId: string;
    password: string;
    memoryLimit?: string;
    command?: string;
    dockerImage?: string;
  },
): Promise<CreateRedisResponse> {
  // NOTE: externalPort is NOT settable here — Dokploy ignores it on create.
  // Use `saveDokployRedisExternalPort` between create and deploy.
  const body = {
    name: params.name,
    appName: params.appName,
    projectId: params.projectId,
    environmentId: params.environmentId,
    dockerImage: params.dockerImage ?? "redis:7-alpine",
    // Dokploy's redis.create uses `databasePassword` (verified empirically
    // against API 400 response, despite Redis having no concept of database).
    databasePassword: params.password,
    memoryLimit: params.memoryLimit ?? "160m",
    command:
      params.command ??
      'redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru --save ""',
    description: "Provisioned by Agentic Builder kickoff",
  };
  return dokployPost<CreateRedisResponse>(
    `${params.baseUrl}/api/redis.create`,
    params.token,
    body,
  );
}

export async function deployDokployRedis(
  params: DokployBase & { redisId: string },
): Promise<void> {
  await dokployPost(`${params.baseUrl}/api/redis.deploy`, params.token, {
    redisId: params.redisId,
  });
}

/**
 * Set the host port for a Redis service. Must be called between `create` and
 * `deploy` (Dokploy ignores `externalPort` in the create body).
 */
export async function saveDokployRedisExternalPort(
  params: DokployBase & { redisId: string; externalPort: number },
): Promise<void> {
  await dokployPost(`${params.baseUrl}/api/redis.saveExternalPort`, params.token, {
    redisId: params.redisId,
    externalPort: params.externalPort,
  });
}

export interface DokployRedisDetail {
  redisId: string;
  appName: string;
  name: string;
  externalPort: number | null;
  password: string;
  applicationStatus: string;
  serverIp?: string | null;
}

export async function getDokployRedis(
  params: DokployBase & { redisId: string },
): Promise<DokployRedisDetail> {
  return dokployGet<DokployRedisDetail>(
    `${params.baseUrl}/api/redis.one?redisId=${encodeURIComponent(params.redisId)}`,
    params.token,
  );
}

export async function removeDokployRedis(
  params: DokployBase & { redisId: string },
): Promise<void> {
  await dokployPost(`${params.baseUrl}/api/redis.remove`, params.token, {
    redisId: params.redisId,
  });
}

// ── Postgres service API ────────────────────────────────────────────────────

export interface CreatePostgresResponse {
  postgresId: string;
  appName: string;
}

export async function createDokployPostgres(
  params: DokployBase & {
    name: string;
    appName: string;
    projectId: string;
    environmentId: string;
    databaseName: string;
    databaseUser: string;
    databasePassword: string;
    memoryLimit?: string;
    dockerImage?: string;
  },
): Promise<CreatePostgresResponse> {
  // NOTE: externalPort is NOT settable here — Dokploy ignores it on create.
  // Use `saveDokployPostgresExternalPort` between create and deploy.
  const body = {
    name: params.name,
    appName: params.appName,
    projectId: params.projectId,
    environmentId: params.environmentId,
    dockerImage: params.dockerImage ?? "postgres:16-alpine",
    databaseName: params.databaseName,
    databaseUser: params.databaseUser,
    databasePassword: params.databasePassword,
    memoryLimit: params.memoryLimit ?? "512m",
    description: "Provisioned by Agentic Builder kickoff",
  };
  return dokployPost<CreatePostgresResponse>(
    `${params.baseUrl}/api/postgres.create`,
    params.token,
    body,
  );
}

export async function deployDokployPostgres(
  params: DokployBase & { postgresId: string },
): Promise<void> {
  await dokployPost(`${params.baseUrl}/api/postgres.deploy`, params.token, {
    postgresId: params.postgresId,
  });
}

/**
 * Set the host port for a Postgres service. Must be called between `create`
 * and `deploy` (Dokploy ignores `externalPort` in the create body).
 */
export async function saveDokployPostgresExternalPort(
  params: DokployBase & { postgresId: string; externalPort: number },
): Promise<void> {
  await dokployPost(
    `${params.baseUrl}/api/postgres.saveExternalPort`,
    params.token,
    {
      postgresId: params.postgresId,
      externalPort: params.externalPort,
    },
  );
}

export interface DokployPostgresDetail {
  postgresId: string;
  appName: string;
  name: string;
  externalPort: number | null;
  databaseName: string;
  databaseUser: string;
  databasePassword: string;
  applicationStatus: string;
  serverIp?: string | null;
}

export async function getDokployPostgres(
  params: DokployBase & { postgresId: string },
): Promise<DokployPostgresDetail> {
  return dokployGet<DokployPostgresDetail>(
    `${params.baseUrl}/api/postgres.one?postgresId=${encodeURIComponent(params.postgresId)}`,
    params.token,
  );
}

export async function removeDokployPostgres(
  params: DokployBase & { postgresId: string },
): Promise<void> {
  await dokployPost(`${params.baseUrl}/api/postgres.remove`, params.token, {
    postgresId: params.postgresId,
  });
}

interface DeploymentSummary {
  deploymentId: string;
  status: string;
  logPath: string | null;
}

interface ComposeStatusResponse {
  composeStatus: "idle" | "running" | "done" | "error";
  domains: Array<{ host: string; https: boolean }>;
  deployments?: DeploymentSummary[];
}

export async function pollDeployStatus(
  params: DokployBase & {
    composeId: string;
    intervalMs: number;
    timeoutMs: number;
  }
): Promise<string> {
  const deadline = Date.now() + params.timeoutMs;

  while (Date.now() < deadline) {
    const data = await dokployGet<ComposeStatusResponse>(
      `${params.baseUrl}/api/compose.one?composeId=${params.composeId}`,
      params.token
    );

    console.log("[dokploy] poll status:", JSON.stringify(data));
    if (data.composeStatus === "done") {
      const domain = data.domains[0];
      if (domain) {
        return `${domain.https ? "https" : "http"}://${domain.host}`;
      }
      return `${params.baseUrl}/dashboard/compose/${params.composeId}`;
    }

    if (data.composeStatus === "error") {
      const failedDeployment = data.deployments?.find((d) => d.status === "error");
      if (failedDeployment?.deploymentId) {
        try {
          const logData = await dokployGet<{ logs: string }>(
            `${params.baseUrl}/api/deployment.one?deploymentId=${failedDeployment.deploymentId}`,
            params.token,
          );
          console.log("[dokploy] deployment error logs:", logData.logs?.slice(-2000));
          throw new Error(`Dokploy deploy failed. Logs:\n${logData.logs?.slice(-1000) ?? "(no logs)"}`);
        } catch (logErr) {
          if (logErr instanceof Error && logErr.message.startsWith("Dokploy deploy failed")) throw logErr;
        }
      }
      throw new Error("Dokploy deploy failed");
    }

    await new Promise((r) => setTimeout(r, params.intervalMs));
  }

  throw new Error("Dokploy deploy timed out after waiting");
}
