interface DokployBase {
  baseUrl: string;
  token: string;
}

async function dokployPost<T>(url: string, token: string, body: unknown): Promise<T> {
  const res = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": token,
    },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error(`Dokploy API error ${res.status}: ${text}`);
  }
  return res.json() as Promise<T>;
}

async function dokployGet<T>(url: string, token: string): Promise<T> {
  const res = await fetch(url, {
    headers: { "x-api-key": token },
  });
  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error(`Dokploy API error ${res.status}: ${text}`);
  }
  return res.json() as Promise<T>;
}

interface CreateProjectResponse {
  project: { projectId: string };
  environment: { environmentId: string };
}

export async function createDokployProject(
  params: DokployBase & { name: string }
): Promise<{ projectId: string; environmentId: string }> {
  const data = await dokployPost<CreateProjectResponse>(
    `${params.baseUrl}/api/project.create`,
    params.token,
    { name: params.name, description: "Generated by Agentic Builder" }
  );
  return {
    projectId: data.project.projectId,
    environmentId: data.environment.environmentId,
  };
}

export async function createDokployCompose(
  params: DokployBase & { name: string; projectId: string; environmentId: string }
): Promise<{ composeId: string; appName: string }> {
  const data = await dokployPost<{ composeId: string; appName: string }>(
    `${params.baseUrl}/api/compose.create`,
    params.token,
    { name: params.name, projectId: params.projectId, environmentId: params.environmentId }
  );
  return { composeId: data.composeId, appName: data.appName };
}

export async function createDokployDomain(
  params: DokployBase & { composeId: string; host: string; serviceName: string }
): Promise<void> {
  await dokployPost(
    `${params.baseUrl}/api/domain.create`,
    params.token,
    {
      composeId: params.composeId,
      host: params.host,
      port: 80,
      serviceName: params.serviceName,
      certificateType: "none",
    }
  );
}

export async function updateDokployCompose(
  params: DokployBase & {
    composeId: string;
    repository: string;
    branch: string;
    env: string;
  }
): Promise<void> {
  const body = {
    composeId: params.composeId,
    sourceType: "git",
    customGitUrl: params.repository,
    customGitBranch: params.branch,
    composeType: "docker-compose",
    env: params.env,
  };
  console.log("[dokploy] compose.update request:", JSON.stringify(body));
  const res = await dokployPost<unknown>(`${params.baseUrl}/api/compose.update`, params.token, body);
  console.log("[dokploy] compose.update response:", JSON.stringify(res));
}

export async function deployDokployCompose(
  params: DokployBase & { composeId: string }
): Promise<void> {
  await dokployPost(
    `${params.baseUrl}/api/compose.deploy`,
    params.token,
    { composeId: params.composeId }
  );
}

interface DeploymentSummary {
  deploymentId: string;
  status: string;
  logPath: string | null;
}

interface ComposeStatusResponse {
  composeStatus: "idle" | "running" | "done" | "error";
  domains: Array<{ host: string; https: boolean }>;
  deployments?: DeploymentSummary[];
}

export async function pollDeployStatus(
  params: DokployBase & {
    composeId: string;
    intervalMs: number;
    timeoutMs: number;
  }
): Promise<string> {
  const deadline = Date.now() + params.timeoutMs;

  while (Date.now() < deadline) {
    const data = await dokployGet<ComposeStatusResponse>(
      `${params.baseUrl}/api/compose.one?composeId=${params.composeId}`,
      params.token
    );

    console.log("[dokploy] poll status:", JSON.stringify(data));
    if (data.composeStatus === "done") {
      const domain = data.domains[0];
      if (domain) {
        return `${domain.https ? "https" : "http"}://${domain.host}`;
      }
      return `${params.baseUrl}/dashboard/compose/${params.composeId}`;
    }

    if (data.composeStatus === "error") {
      const failedDeployment = data.deployments?.find((d) => d.status === "error");
      if (failedDeployment?.deploymentId) {
        try {
          const logData = await dokployGet<{ logs: string }>(
            `${params.baseUrl}/api/deployment.one?deploymentId=${failedDeployment.deploymentId}`,
            params.token,
          );
          console.log("[dokploy] deployment error logs:", logData.logs?.slice(-2000));
          throw new Error(`Dokploy deploy failed. Logs:\n${logData.logs?.slice(-1000) ?? "(no logs)"}`);
        } catch (logErr) {
          if (logErr instanceof Error && logErr.message.startsWith("Dokploy deploy failed")) throw logErr;
        }
      }
      throw new Error("Dokploy deploy failed");
    }

    await new Promise((r) => setTimeout(r, params.intervalMs));
  }

  throw new Error("Dokploy deploy timed out after waiting");
}
