interface DokployBase {
  baseUrl: string;
  token: string;
}

async function dokployPost<T>(url: string, token: string, body: unknown): Promise<T> {
  const res = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": token,
    },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error(`Dokploy API error ${res.status}: ${text}`);
  }
  return res.json() as Promise<T>;
}

async function dokployGet<T>(url: string, token: string): Promise<T> {
  const res = await fetch(url, {
    headers: { "x-api-key": token },
  });
  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error(`Dokploy API error ${res.status}: ${text}`);
  }
  return res.json() as Promise<T>;
}

export async function createDokployProject(
  params: DokployBase & { name: string }
): Promise<string> {
  const data = await dokployPost<{ projectId: string }>(
    `${params.baseUrl}/api/project.create`,
    params.token,
    { name: params.name, description: "Generated by Agentic Builder" }
  );
  return data.projectId;
}

export async function createDokployCompose(
  params: DokployBase & { name: string; projectId: string }
): Promise<string> {
  const data = await dokployPost<{ composeId: string }>(
    `${params.baseUrl}/api/compose.create`,
    params.token,
    { name: params.name, projectId: params.projectId }
  );
  return data.composeId;
}

export async function updateDokployCompose(
  params: DokployBase & {
    composeId: string;
    repository: string;
    branch: string;
    env: string;
  }
): Promise<void> {
  await dokployPost(
    `${params.baseUrl}/api/compose.update`,
    params.token,
    {
      composeId: params.composeId,
      repository: params.repository,
      branch: params.branch,
      composeType: "docker-compose",
      env: params.env,
    }
  );
}

export async function deployDokployCompose(
  params: DokployBase & { composeId: string }
): Promise<void> {
  await dokployPost(
    `${params.baseUrl}/api/compose.deploy`,
    params.token,
    { composeId: params.composeId }
  );
}

interface ComposeStatusResponse {
  composeStatus: "idle" | "running" | "done" | "error";
  domains: Array<{ host: string; https: boolean }>;
}

export async function pollDeployStatus(
  params: DokployBase & {
    composeId: string;
    intervalMs: number;
    timeoutMs: number;
  }
): Promise<string> {
  const deadline = Date.now() + params.timeoutMs;

  while (Date.now() < deadline) {
    const data = await dokployGet<ComposeStatusResponse>(
      `${params.baseUrl}/api/compose.one?composeId=${params.composeId}`,
      params.token
    );

    if (data.composeStatus === "done") {
      const domain = data.domains[0];
      if (domain) {
        return `${domain.https ? "https" : "http"}://${domain.host}`;
      }
      return `${params.baseUrl}/dashboard/compose/${params.composeId}`;
    }

    if (data.composeStatus === "error") {
      throw new Error("Dokploy deploy failed");
    }

    await new Promise((r) => setTimeout(r, params.intervalMs));
  }

  throw new Error("Dokploy deploy timed out after waiting");
}
