/**
 * JWT helpers using `jsonwebtoken`.
 *
 * Reads `AUTH_JWT_SECRET` from process.env (auto-generated by the Setup
 * Wizard). Throws a typed error at first use when the secret is missing so
 * boot-time misconfigurations surface immediately instead of silently
 * signing with `"undefined"`.
 */

import jwt, { type SignOptions, type JwtPayload } from "jsonwebtoken";

function readSecret(): string {
  const secret = process.env.AUTH_JWT_SECRET;
  if (!secret || secret.trim().length < 16) {
    throw new Error(
      "AUTH_JWT_SECRET missing or too short (<16 chars). Generate one with " +
        "`openssl rand -hex 32` and add to backend/.env.",
    );
  }
  return secret;
}

export function signJwt(
  payload: Record<string, unknown>,
  expiresIn: SignOptions["expiresIn"] = "7d",
): string {
  return jwt.sign(payload, readSecret(), { expiresIn });
}

export function verifyJwt(token: string): JwtPayload {
  const decoded = jwt.verify(token, readSecret());
  if (typeof decoded === "string") {
    throw new Error("Unexpected string JWT payload");
  }
  return decoded;
}
