/**
 * Generate `SETUP.md` — a human-readable companion doc that lives in the
 * generated project root. The Wizard writes it alongside `.env` so 6 months
 * later a teammate can still figure out which keys were supplied / skipped /
 * deferred, and how to fill in the rest.
 */

import {
  ENV_KEY_CATALOG,
  getEnvKeyMeta,
  type EnvKeyMeta,
  type EnvKeyCategory,
} from "./env-key-catalog";

export type SetupKeyState = "provided" | "skipped" | "auto" | "deferred";

export interface SetupKeyEntry {
  key: string;
  state: SetupKeyState;
  /** Optional masked-display hint shown in the doc — never the actual secret. */
  hint?: string;
}

export interface SetupMdInput {
  /** Project display name from PRD line 1. */
  projectName?: string;
  /** "bundled" → docker-compose default; "byo" → user-supplied DB/Redis URLs. */
  infraChoice: "bundled" | "byo";
  /** All env keys touched in the Wizard, with their states. */
  keys: SetupKeyEntry[];
}

export function generateSetupMd(input: SetupMdInput): string {
  const { projectName = "Generated project", infraChoice, keys } = input;
  const byCategory = new Map<EnvKeyCategory, SetupKeyEntry[]>();
  for (const entry of keys) {
    const meta = getEnvKeyMeta(entry.key);
    if (!byCategory.has(meta.category)) byCategory.set(meta.category, []);
    byCategory.get(meta.category)!.push(entry);
  }

  const lines: string[] = [];
  lines.push(`# Setup — ${projectName}`);
  lines.push("");
  lines.push(
    "> This document is auto-generated by the Setup Wizard. It records what was",
  );
  lines.push(
    "> configured when the project was first scaffolded. Update it manually if",
  );
  lines.push("> you add or rotate credentials later.");
  lines.push("");
  lines.push(`Generated: ${new Date().toISOString()}`);
  lines.push("");

  // ── Quick start ──
  lines.push("## 1. Quick start");
  lines.push("");
  if (infraChoice === "bundled") {
    lines.push("```bash");
    lines.push("# Bring up Postgres + TimescaleDB + Redis via the included compose file:");
    lines.push("docker compose up -d");
    lines.push("");
    lines.push("# Run migrations (auto on first boot when AUTO_MIGRATE=true):");
    lines.push("pnpm --filter backend migrate");
    lines.push("");
    lines.push("# Start the app:");
    lines.push("pnpm dev");
    lines.push("```");
  } else {
    lines.push("```bash");
    lines.push("# Make sure DATABASE_URL + REDIS_URL in .env point to live instances.");
    lines.push("pnpm --filter backend migrate");
    lines.push("pnpm dev");
    lines.push("```");
  }
  lines.push("");

  // ── Infrastructure ──
  lines.push("## 2. Infrastructure");
  lines.push("");
  if (infraChoice === "bundled") {
    lines.push(
      "**Bundled.** `docker-compose.yml` brings up PostgreSQL 16 + TimescaleDB extension + Redis 7 on default ports. No external setup required.",
    );
  } else {
    lines.push(
      "**Bring-your-own.** `DATABASE_URL` and `REDIS_URL` in `.env` point to instances you manage. Make sure:",
    );
    lines.push("");
    lines.push("- PostgreSQL is **version 16** with the **TimescaleDB extension installed and enabled** in the target database.");
    lines.push("- Redis is **version 7+**.");
    lines.push("- Network access from the app host to both is open.");
  }
  lines.push("");

  // ── Credentials by category ──
  const order: EnvKeyCategory[] = ["auto", "vendor", "auth", "deploy"];
  const titles: Record<EnvKeyCategory, string> = {
    infrastructure: "Infrastructure",
    auto: "Auto-generated secrets",
    vendor: "Third-party vendor API keys",
    auth: "Mail / login credentials",
    deploy: "Deployment credentials (optional — fill before `deploy.sh`)",
  };

  for (const cat of order) {
    const entries = byCategory.get(cat);
    if (!entries || entries.length === 0) continue;
    lines.push(`## 3.${order.indexOf(cat) + 1} ${titles[cat]}`);
    lines.push("");
    lines.push(renderCategoryTable(entries));
    lines.push("");

    // Add per-key details below the table
    for (const entry of entries) {
      const meta = getEnvKeyMeta(entry.key);
      lines.push(`#### \`${meta.key}\` — ${stateBadge(entry.state)}`);
      lines.push("");
      lines.push(`**Feature**: ${meta.feature}`);
      if (meta.signupUrl) {
        lines.push("");
        lines.push(
          `**Where to obtain**: ${meta.signupUrl}${meta.freeTierOk ? " (free tier suffices for v1)" : ""}`,
        );
      }
      if (entry.state === "skipped" || entry.state === "deferred") {
        lines.push("");
        lines.push(`**If left empty**: ${meta.skipBehavior}`);
      }
      lines.push("");
    }
  }

  // ── How to fill skipped keys later ──
  const skippedOrDeferred = keys.filter(
    (k) => k.state === "skipped" || k.state === "deferred",
  );
  if (skippedOrDeferred.length > 0) {
    lines.push("## 4. Filling in skipped keys later");
    lines.push("");
    lines.push("Edit `.env` and add a value for any of the keys below, then restart the backend.");
    lines.push("Lazy adapters in the codebase pick up the new key without a code change:");
    lines.push("");
    lines.push("```bash");
    for (const k of skippedOrDeferred) {
      lines.push(`${k.key}=`);
    }
    lines.push("```");
    lines.push("");
  }

  return lines.join("\n");
}

function renderCategoryTable(entries: SetupKeyEntry[]): string {
  const rows = entries.map((entry) => {
    const meta = getEnvKeyMeta(entry.key);
    return `| \`${meta.key}\` | ${stateBadge(entry.state)} | ${meta.feature.replace(/\|/g, "\\|")} |`;
  });
  return [
    "| Key | Status | Feature |",
    "|-----|--------|---------|",
    ...rows,
  ].join("\n");
}

function stateBadge(state: SetupKeyState): string {
  switch (state) {
    case "provided": return "✅ Provided";
    case "auto":     return "🔑 Auto-generated";
    case "skipped":  return "⚠️ Skipped";
    case "deferred": return "⏳ Deferred";
  }
}

// Re-export for callers that want the catalog directly.
export { ENV_KEY_CATALOG, getEnvKeyMeta, type EnvKeyMeta };
