/**
 * Phase-2 subsystem orchestrator (planning core).
 *
 * Turns a validated subsystem manifest + the whole-system task list into a
 * LAYERED build plan: for each topological layer, the set of subsystems to build
 * (in parallel), each with the exact task subset it should code — its own tasks
 * plus their transitive dependencies (so the subset is self-consistent / compiles).
 *
 * Task → subsystem assignment uses, in order:
 *   1. `task.subsystem` when set (tasks generated by a scoped per-subsystem
 *      breakdown are born tagged), else
 *   2. file-prefix match: a task whose created/modified files live under one of a
 *      subsystem's `ownedModules` paths belongs to that subsystem.
 *
 * The planning functions are pure (no IO / no LLM) and unit-tested. The actual
 * coding run is supplied by the caller as an injected callback, so the loop is
 * testable and reuses the existing per-subset coding pipeline.
 */

import type { KickoffWorkItem } from "../types";
import type { SubsystemManifest } from "./types";
import { validateSubsystemManifest } from "./validate";

// ─── Task ↔ subsystem assignment ────────────────────────────────────────────

function taskFiles(task: KickoffWorkItem): string[] {
  const f = task.files;
  if (!f) return [];
  const norm = (s: string) => s.replace(/\\/g, "/");
  if (Array.isArray(f)) return f.map(norm);
  return [...(f.creates ?? []), ...(f.modifies ?? []), ...(f.reads ?? [])].map(norm);
}

/** True when `file` is inside `moduleRoot` (path-prefix, segment-aware). */
function isUnderModule(file: string, moduleRoot: string): boolean {
  const root = moduleRoot.replace(/\/+$/, "");
  return file === root || file.startsWith(root + "/");
}

/**
 * Assign each task to at most one subsystem. Returns the assignment map plus the
 * ids of tasks that matched no subsystem (cross-cutting/foundation tasks — e.g.
 * scaffold, shared models — which belong to the Phase-1 shared foundation, not a
 * subsystem).
 */
export function assignTasksToSubsystems(
  tasks: KickoffWorkItem[],
  manifest: SubsystemManifest,
): { bySubsystem: Map<string, string[]>; unassigned: string[] } {
  const bySubsystem = new Map<string, string[]>();
  for (const s of manifest.subsystems) bySubsystem.set(s.id, []);
  const unassigned: string[] = [];

  for (const task of tasks) {
    // 1. explicit tag wins
    if (task.subsystem && bySubsystem.has(task.subsystem)) {
      bySubsystem.get(task.subsystem)!.push(task.id);
      continue;
    }
    // 2. file-prefix match against ownedModules
    const files = taskFiles(task);
    let owner: string | null = null;
    for (const s of manifest.subsystems) {
      if (files.some((file) => s.ownedModules.some((m) => isUnderModule(file, m)))) {
        owner = s.id;
        break;
      }
    }
    if (owner) bySubsystem.get(owner)!.push(task.id);
    else unassigned.push(task.id);
  }
  return { bySubsystem, unassigned };
}

// ─── Transitive dependency closure ──────────────────────────────────────────

/**
 * Expand a set of task ids to include all of their transitive `dependencies`,
 * so a per-subsystem coding subset is self-consistent. Dependencies that fall
 * outside the provided task list are dropped (assumed already built / foundation).
 */
export function closeOverDependencies(
  seedIds: Iterable<string>,
  tasks: KickoffWorkItem[],
): string[] {
  const byId = new Map(tasks.map((t) => [t.id, t]));
  const result = new Set<string>();
  const stack = [...seedIds];
  while (stack.length) {
    const id = stack.pop()!;
    if (result.has(id)) continue;
    if (!byId.has(id)) continue;
    result.add(id);
    for (const dep of byId.get(id)!.dependencies ?? []) {
      if (!result.has(dep)) stack.push(dep);
    }
  }
  return [...result];
}

// ─── Layered build plan ─────────────────────────────────────────────────────

export interface SubsystemBuildStep {
  layer: number;
  subsystemId: string;
  /** Tasks to code for this subsystem (own tasks + transitive deps), order-preserving. */
  taskIds: string[];
  /** Subsystem ids that must be built before this one. */
  dependsOn: string[];
  /** API endpoints in scope when validating this build — owned by this subsystem
   *  plus its transitive subsystem-dependencies (all guaranteed already built).
   *  Written to the active-scope sidecar so gates skip not-yet-built domains. */
  scopeEndpoints: string[];
}

/** Transitive subsystem-dependency closure (including self) over the DAG. */
function subsystemDepClosure(manifest: SubsystemManifest): Map<string, Set<string>> {
  const depsOf = new Map(manifest.subsystems.map((s) => [s.id, s.dependsOn]));
  const closure = new Map<string, Set<string>>();
  for (const s of manifest.subsystems) {
    const seen = new Set<string>();
    const stack = [s.id];
    while (stack.length) {
      const id = stack.pop()!;
      if (seen.has(id)) continue;
      seen.add(id);
      for (const d of depsOf.get(id) ?? []) if (!seen.has(d)) stack.push(d);
    }
    closure.set(s.id, seen);
  }
  return closure;
}

export interface SubsystemBuildPlan {
  /** Steps grouped by topological layer; steps within a layer can run in parallel. */
  layers: SubsystemBuildStep[][];
  /** Tasks owned by no subsystem (shared foundation / cross-cutting). */
  unassignedTaskIds: string[];
  /** Validation problems (non-empty → plan is empty). */
  errors: string[];
}

/**
 * Build the ordered, layered plan. Tasks keep their original relative order
 * within each subsystem's `taskIds`. Returns `errors` (and empty layers) if the
 * manifest is invalid.
 */
export function planSubsystemBuilds(
  manifest: SubsystemManifest,
  tasks: KickoffWorkItem[],
): SubsystemBuildPlan {
  const validation = validateSubsystemManifest(manifest);
  if (!validation.ok) {
    return { layers: [], unassignedTaskIds: [], errors: validation.errors };
  }

  const { bySubsystem, unassigned } = assignTasksToSubsystems(tasks, manifest);
  const taskOrder = new Map(tasks.map((t, i) => [t.id, i]));
  const depsOf = new Map(manifest.subsystems.map((s) => [s.id, s.dependsOn]));
  const endpointsOf = new Map(manifest.subsystems.map((s) => [s.id, s.ownedApiEndpoints]));
  const depClosure = subsystemDepClosure(manifest);

  const layers: SubsystemBuildStep[][] = validation.buildLayers.map(
    (layerIds, layerIdx) =>
      layerIds.map((subsystemId) => {
        const own = bySubsystem.get(subsystemId) ?? [];
        const closed = closeOverDependencies(own, tasks).sort(
          (a, b) => (taskOrder.get(a) ?? 0) - (taskOrder.get(b) ?? 0),
        );
        // Scope = endpoints owned by this subsystem + its transitive deps
        // (all guaranteed built before this step runs).
        const scope = new Set<string>();
        for (const dep of depClosure.get(subsystemId) ?? [subsystemId]) {
          for (const ep of endpointsOf.get(dep) ?? []) scope.add(ep);
        }
        return {
          layer: layerIdx,
          subsystemId,
          taskIds: closed,
          dependsOn: depsOf.get(subsystemId) ?? [],
          scopeEndpoints: [...scope].sort(),
        };
      }),
  );

  return { layers, unassignedTaskIds: unassigned, errors: [] };
}

// ─── Runner (injected coding callback) ──────────────────────────────────────

export type SubsystemCodingRunner = (
  step: SubsystemBuildStep,
) => Promise<{ ok: boolean; summary?: string }>;

export interface SubsystemRunResult {
  subsystemId: string;
  layer: number;
  status: "completed" | "failed" | "skipped";
  summary?: string;
}

export interface RunSubsystemsOptions {
  /** Subsystem ids already completed (from checkpoints) — skipped this run. */
  alreadyDone?: Set<string>;
  /** Called after each subsystem finishes (to persist a checkpoint). */
  onStepDone?: (result: SubsystemRunResult) => Promise<void> | void;
  /** Stop the whole run on the first failure (default true) — a dependent layer
   *  cannot safely build on a broken dependency. */
  stopOnFailure?: boolean;
}

/**
 * Execute the plan layer-by-layer. Each subsystem is coded via the injected
 * `runCoding`. Failures stop dependent layers (by default) since later layers
 * build on earlier ones.
 *
 * Within a layer, subsystems run SEQUENTIALLY (one `runCoding` at a time), not
 * concurrently. The coding route shares process-global, file-backed state across
 * calls — the active-subsystem-scope sidecar
 * (`.blueprint/active-subsystem-scope.json`), the session checkpoint
 * (`.blueprint/last-coding-session.json`), and the single `codeOutputDir`.
 * Building a layer's members concurrently would let those clobber each other:
 * e.g. domain B's `writeActiveScope` overwrites the sidecar that domain A's gates
 * read moments later, so A is validated against B's endpoint scope. Layers were
 * originally a parallelism affordance; we keep their dependency ORDER but run the
 * members in series for safety. (Re-introducing intra-layer parallelism requires
 * isolating the scope/checkpoint per coding request.)
 */
export async function runSubsystemBuilds(
  plan: SubsystemBuildPlan,
  runCoding: SubsystemCodingRunner,
  opts?: RunSubsystemsOptions,
): Promise<SubsystemRunResult[]> {
  const done = new Set(opts?.alreadyDone ?? []);
  const stopOnFailure = opts?.stopOnFailure ?? true;
  const results: SubsystemRunResult[] = [];

  const recordResult = async (r: SubsystemRunResult): Promise<void> => {
    results.push(r);
    if (opts?.onStepDone) await opts.onStepDone(r);
    if (r.status === "completed") done.add(r.subsystemId);
  };

  for (const layer of plan.layers) {
    let layerFailed = false;
    // Sequential within the layer — see the function doc for why.
    for (const step of layer) {
      if (done.has(step.subsystemId)) {
        await recordResult({ subsystemId: step.subsystemId, layer: step.layer, status: "skipped" });
        continue;
      }
      let result: SubsystemRunResult;
      try {
        const r = await runCoding(step);
        result = {
          subsystemId: step.subsystemId,
          layer: step.layer,
          status: r.ok ? "completed" : "failed",
          summary: r.summary,
        };
      } catch (err) {
        result = {
          subsystemId: step.subsystemId,
          layer: step.layer,
          status: "failed",
          summary: err instanceof Error ? err.message : String(err),
        };
      }
      await recordResult(result);
      if (result.status === "failed") layerFailed = true;
    }
    // A dependent layer cannot safely build on a broken dependency — stop here.
    if (stopOnFailure && layerFailed) break;
  }

  return results;
}
