/**
 * Post-processing: guarantee a single "Frontend Foundation" task that ships the
 * shared design system as CODE — semantic design tokens, shared UI primitives,
 * a layout shell and a router skeleton — and wire every frontend page/component
 * task to read it.
 *
 * Why this exists:
 *   DesignSpec.md is a *guide document*, not shared code. A doc can only inform
 *   an agent; it cannot enforce reuse. When N page agents each transcribe the
 *   spec independently, the same brand colour drifts across pages
 *   (bg-[#7d976b] vs bg-[#6f875f] vs text-[#4c6a3c]), no shared Button exists,
 *   and Card gets re-invented per domain. The fix is code-level: one Foundation
 *   task creates the tokens + primitives, and pages import them.
 *
 *   This pairs with split-multipage-tasks.ts: the page-count cap REDUCES drift
 *   (fewer independent transcriptions); the Foundation ELIMINATES it (everyone
 *   imports the same `<Button>` and `bg-primary` token).
 *
 * Behaviour (augment-or-create, idempotent):
 *   - No-op unless the project has frontend tasks.
 *   - Foundation files already owned by another task are left where they are
 *     (never create the same file twice).
 *   - If an app-shell-ish task already exists (creates router.tsx / main.tsx /
 *     AppLayout / AuthContext — the same anchor task-dep-inference keys on), the
 *     unowned foundation files are merged INTO it and it is relabelled as the
 *     Foundation. Otherwise a fresh P0 Foundation task is synthesised at the
 *     front and IDs are renumbered.
 *   - Every other frontend view/component/page task gets the token file and the
 *     UI barrel added to its `files.reads` so the coding agent actually opens
 *     and imports them.
 *
 * Dependency wiring is left to task-dep-inference.ts, which already makes every
 * view/component task depend on the app-shell anchor — now the Foundation task.
 */

import type { KickoffWorkItem, TaskFilePlan } from "./types";
import { ENABLE_FE_ROUTE_CONSOLIDATION } from "@/lib/langgraph/supervisor/config";

const TOKENS_FILE = "frontend/src/styles/tokens.css";
const UI_BARREL = "frontend/src/components/ui/index.ts";
const INDEX_CSS = "frontend/src/index.css";

// UI primitives are NO LONGER hand-rolled by the Foundation: the scaffold
// pre-installs shadcn-ui components under `frontend/src/components/ui/` plus an
// `index.ts` barrel. The Foundation consumes them; it does not create them.

/** Layout shell + app-shell anchor files (so task-dep-inference locks onto us). */
const LAYOUT_FILES = [
  "frontend/src/components/layout/AppLayout.tsx",
  "frontend/src/components/layout/Sidebar.tsx",
  "frontend/src/components/layout/TopNav.tsx",
];
const SHELL_FILES = [
  "frontend/src/router.tsx",
  "frontend/src/context/AuthContext.tsx",
];

/** Files the Foundation owns, in priority order (tokens first, shell last).
 *  NOTE: shadcn UI primitives + the `index.ts` barrel are PRE-INSTALLED by the
 *  scaffold — they are intentionally NOT in this list (the Foundation consumes
 *  them, never recreates them). */
const FOUNDATION_CREATES = [
  TOKENS_FILE,
  ...LAYOUT_FILES,
  ...SHELL_FILES,
];

/** Sentinel used to detect an already-augmented Foundation description. */
const CONTRACT_MARKER = "DESIGN-SYSTEM CONTRACT";

// Deliverable #4 differs by mode. With route-consolidation ON, the foundation
// ships only a MINIMAL router shell (App→layout + an index route); per-page
// routes are registered later by the `fe_route_consolidation` step once the
// views actually exist (no guessing view paths → no silent 404 / stub views).
// With it OFF (legacy), the foundation pre-registers every route to a lazy view.
const ROUTER_DELIVERABLE = ENABLE_FE_ROUTE_CONSOLIDATION
  ? [
      "  4. MINIMAL router shell (`router.tsx`): wire BrowserRouter + AppLayout",
      "     with ONLY an index/landing route. DO NOT enumerate per-page routes —",
      "     they are registered automatically in a later consolidation step once",
      "     every view exists. Export a default `AppRouter` so App.tsx can import it.",
    ]
  : [
      "  4. Router skeleton (`router.tsx`) with EVERY route pre-registered to its",
      "     (lazy) view — a missing view is then a build error, not a silent 404.",
    ];

const FOUNDATION_DESCRIPTION = [
  "Establish the shared frontend design system as CODE (not a doc) so every",
  "page reuses one visual language instead of re-deriving it.",
  "",
  "Deliverables:",
  `  1. Semantic design tokens in \`${TOKENS_FILE}\`. This file is ALREADY`,
  `     GENERATED by the design step (derived from the DesignSpec) and copied`,
  `     into place, and is ALREADY imported by \`${INDEX_CSS}\`. DO NOT rewrite`,
  "     or overwrite its `@theme` block — CONSUME the existing tokens",
  "     (bg-primary, text-muted, rounded-md, p-4, text-lg). If a genuinely new",
  "     token is required, ADD it using the existing --color-*/--text-*/",
  "     --spacing-*/--radius-* naming; never replace the file.",
  "  2. Shared UI primitives are PRE-INSTALLED as shadcn-ui components in",
  "     `frontend/src/components/ui/` (Button, Input, Label, Textarea, Card,",
  "     Badge, Dialog, Select, Dropdown-menu, Checkbox, Tabs, Tooltip, Table,",
  "     Form, Sonner), re-exported from the `index.ts` barrel. CONSUME them — do NOT",
  "     hand-roll or recreate. Need a component shadcn doesn't ship? Add it via",
  "     `npx shadcn@latest add <name>` (or hand-roll under `components/ui/`",
  "     composing Radix primitives) using the existing tokens, then export it",
  "     from the barrel.",
  "  3. Layout shell (AppLayout + Sidebar + TopNav) and per-role shells.",
  ...ROUTER_DELIVERABLE,
  "  5. Shared AuthContext / providers.",
  "",
  "DESIGN-SYSTEM CONTRACT for all downstream page tasks:",
  "  - Import shadcn primitives from `@/components/ui`; do NOT hand-roll",
  "    buttons/inputs/cards. Need a missing component? add it under",
  "    `components/ui/` and export it from the barrel.",
  "  - Prefer semantic tokens (bg-primary, text-muted, rounded-md, p-4). Only",
  "    fall back to an arbitrary value (bg-[#7d976b]) when no token matches.",
].join("\n");

// ─── helpers ───────────────────────────────────────────────────────────────

function getCreates(t: KickoffWorkItem): string[] {
  if (!t.files) return [];
  if (Array.isArray(t.files)) return t.files;
  return (t.files as TaskFilePlan).creates ?? [];
}

function getReads(t: KickoffWorkItem): string[] {
  if (!t.files || Array.isArray(t.files)) return [];
  return (t.files as TaskFilePlan).reads ?? [];
}

function getModifies(t: KickoffWorkItem): string[] {
  if (!t.files || Array.isArray(t.files)) return [];
  return (t.files as TaskFilePlan).modifies ?? [];
}

function isFrontendTask(t: KickoffWorkItem): boolean {
  return getCreates(t).some((f) => f.startsWith("frontend/"));
}

/** Same app-shell signal task-dep-inference keys on. */
function isShellTask(t: KickoffWorkItem): boolean {
  return getCreates(t).some((f) =>
    /(AuthContext|AppLayout|AppRouter|RootLayout)\.tsx?$|\/router\.tsx?$|\/main\.tsx?$/.test(
      f,
    ),
  );
}

/** Task creates a page/component file that should reuse the shared primitives. */
function createsViewOrComponent(t: KickoffWorkItem): boolean {
  return getCreates(t).some((f) =>
    /^frontend\/src\/(views|pages|components)\//.test(f),
  );
}

function uniq(xs: string[]): string[] {
  return [...new Set(xs)];
}

function renumberTaskIds(tasks: KickoffWorkItem[]): KickoffWorkItem[] {
  const oldToNew = new Map<string, string>();
  tasks.forEach((t, i) => oldToNew.set(t.id, `T-${String(i + 1).padStart(3, "0")}`));
  return tasks.map((t) => ({
    ...t,
    id: oldToNew.get(t.id) ?? t.id,
    dependencies: (t.dependencies ?? []).map((d) => oldToNew.get(d) ?? d),
  }));
}

// ─── main ────────────────────────────────────────────────────────────────────

export function ensureFrontendFoundationTask(
  tasks: KickoffWorkItem[],
): KickoffWorkItem[] {
  // Only relevant to projects with a frontend.
  if (!tasks.some(isFrontendTask)) return tasks;

  // Files already owned by some task — never create them twice.
  const owned = new Set<string>(tasks.flatMap(getCreates));
  const foundationCreates = FOUNDATION_CREATES.filter((f) => !owned.has(f));

  const existingShell = tasks.find(isShellTask);
  const host = existingShell ?? null;

  let result: KickoffWorkItem[];
  let hostId: string;

  if (host) {
    // Augment the existing shell task into the Foundation.
    hostId = host.id;
    const hostCreates = getCreates(host);
    const hostModifies = getModifies(host);
    result = tasks.map((t) => {
      if (t.id !== host.id) return t;
      const alreadyAugmented = (t.description ?? "").includes(CONTRACT_MARKER);
      return {
        ...t,
        title: t.title.toLowerCase().includes("foundation")
          ? t.title
          : "Implement frontend foundation (design tokens, shared UI, shell, router)",
        description: alreadyAugmented
          ? t.description
          : `${FOUNDATION_DESCRIPTION}\n\n---\n\n${t.description ?? ""}`.trim(),
        priority: "P0",
        files: {
          creates: uniq([...hostCreates, ...foundationCreates]),
          // index.css is NOT modified here: the scaffold pre-wires
          // `@import "./styles/tokens.css";`, and tokens.css is in `creates`.
          // Keeping index.css out of the plan prevents a worker rewrite from
          // dropping the import edge (the music-school dead-theme failure).
          modifies: uniq(hostModifies),
          reads: getReads(t),
        },
      };
    });
  } else {
    // No shell task — synthesise one at the front.
    hostId = "T-FND";
    const foundation: KickoffWorkItem = {
      id: hostId,
      phase: "Frontend",
      title: "Implement frontend foundation (design tokens, shared UI, shell, router)",
      description: FOUNDATION_DESCRIPTION,
      estimatedHours: 6,
      executionKind: "ai_autonomous",
      priority: "P0",
      dependencies: [],
      files: {
        // Guarantee the shell anchor files exist even if none were owned.
        creates: uniq([...foundationCreates, ...SHELL_FILES]),
        // index.css intentionally omitted — scaffold pre-wires the
        // `@import "./styles/tokens.css";` edge; tokens.css is in `creates`.
        modifies: [],
        reads: [],
      },
    };
    result = [foundation, ...tasks];
  }

  // Wire every other frontend page/component task to READ the tokens + barrel,
  // so the coding agent opens and imports them instead of re-deriving styling.
  result = result.map((t) => {
    if (t.id === hostId || !createsViewOrComponent(t)) return t;
    const reads = uniq([...getReads(t), TOKENS_FILE, UI_BARREL]);
    const creates = getCreates(t);
    const modifies = getModifies(t);
    return { ...t, files: { creates, modifies, reads } };
  });

  // Renumber only when we synthesised a new task (to keep a clean sequence and
  // avoid the placeholder "T-FND" id leaking downstream). Augmenting an
  // existing task preserves all ids, so no renumber is needed.
  return existingShell ? result : renumberTaskIds(result);
}
