import path from "path";
import type { PrototypeMarker } from "@/lib/pipeline/prototype-marker";
import type { PrdSpec } from "@/lib/requirements/prd-spec-types";

/**
 * Context appended to the task-breakdown prompt when a prototype exists. It tells
 * the planner that these frontend page files ALREADY EXIST (generated by the
 * prototype step) so page tasks must go in `files.modifies` (wire logic into the
 * existing page) — NOT `files.creates`. When `prdSpec` is supplied, it also lists
 * each page's already-inlined `CMP-*` component IDs so the planner does not emit a
 * separate `files.creates` task to "build" a component that already exists inline
 * in the prototype's markup. Returns '' when there is no marker, so the legacy
 * breakdown is byte-for-byte unchanged.
 */
export function buildPrototypeBreakdownContext(
  marker: PrototypeMarker | null,
  prdSpec?: PrdSpec | null,
): string {
  if (!marker || marker.pages.length === 0) return "";

  const pageById = new Map((prdSpec?.pages ?? []).map((p) => [p.id, p]));
  const allCmpIds: string[] = [];

  const rows = marker.pages
    .map((p) => {
      const rel = p.file.startsWith("frontend/") ? p.file : path.posix.join("frontend", p.file);
      const prdPage = pageById.get(p.pageId);
      const cmpIds = prdPage?.interactiveComponents.map((c) => c.id) ?? [];
      allCmpIds.push(...cmpIds);
      const cmpSuffix = cmpIds.length > 0 ? ` — already implements ${cmpIds.join(", ")}` : "";
      return `- ${rel}  (route ${p.route})${cmpSuffix}`;
    })
    .join("\n");

  const componentBlock =
    allCmpIds.length > 0
      ? [
          ``,
          `These component IDs are already implemented — inline, inside the pages`,
          `listed above (they were part of the prototype's markup, not separate`,
          `component files): ${allCmpIds.join(", ")}.`,
          `Do NOT emit a task whose \`files.creates\` builds a standalone component`,
          `file to cover one of these IDs. Cover it via the matching page's MODIFY`,
          `task instead (add it to that task's \`coversRequirementIds\`).`,
        ]
      : [];

  return [
    ``,
    `## PROTOTYPE ALREADY EXISTS — frontend pages are pre-built (IMPORTANT)`,
    `A prototype step already generated these frontend page files (static markup +`,
    `styling, with \`// TODO(logic)\` seams). They ARE on disk:`,
    rows,
    ``,
    `For EACH of these pages, the frontend task MUST:`,
    `- put the page file in \`files.modifies\` (NOT \`files.creates\`) — the file already exists;`,
    `- describe the work as "wire logic / data / handlers into the existing <file>" and`,
    `  say "MODIFY existing <file>" in sub-steps — NEVER "create";`,
    `- preserve the existing markup/styling; only fill the \`// TODO(logic)\` seams.`,
    `Do NOT emit a task that creates these files from scratch. Pages NOT listed above`,
    `(PRD pages with no prototype file) are created normally.`,
    ...componentBlock,
  ].join("\n");
}
