import path from "path";
import type { PrototypeMarker } from "@/lib/pipeline/prototype-marker";

/**
 * Context appended to the task-breakdown prompt when a prototype exists. It tells
 * the planner that these frontend page files ALREADY EXIST (generated by the
 * prototype step) so page tasks must go in `files.modifies` (wire logic into the
 * existing page) — NOT `files.creates`. Returns '' when there is no marker, so the
 * legacy breakdown is byte-for-byte unchanged.
 */
export function buildPrototypeBreakdownContext(marker: PrototypeMarker | null): string {
  if (!marker || marker.pages.length === 0) return "";
  const rows = marker.pages
    .map((p) => {
      const rel = p.file.startsWith("frontend/") ? p.file : path.posix.join("frontend", p.file);
      return `- ${rel}  (route ${p.route})`;
    })
    .join("\n");
  return [
    ``,
    `## PROTOTYPE ALREADY EXISTS — frontend pages are pre-built (IMPORTANT)`,
    `A prototype step already generated these frontend page files (static markup +`,
    `styling, with \`// TODO(logic)\` seams). They ARE on disk:`,
    rows,
    ``,
    `For EACH of these pages, the frontend task MUST:`,
    `- put the page file in \`files.modifies\` (NOT \`files.creates\`) — the file already exists;`,
    `- describe the work as "wire logic / data / handlers into the existing <file>" and`,
    `  say "MODIFY existing <file>" in sub-steps — NEVER "create";`,
    `- preserve the existing markup/styling; only fill the \`// TODO(logic)\` seams.`,
    `Do NOT emit a task that creates these files from scratch. Pages NOT listed above`,
    `(PRD pages with no prototype file) are created normally.`,
  ].join("\n");
}
