/**
 * Post-processing: cap the number of view files per Frontend task, then
 * re-sequence all task IDs.
 *
 * Why a CAP and not a one-page-per-task split:
 *   The original missing-page 404s came from a *single* task being assigned
 *   too many view files — the coding agent ran out of attention/budget and
 *   silently skipped some pages. Splitting all the way down to one page per
 *   task fixed the 404s but fragmented styling: each page is then generated by
 *   an independent agent that never sees the others, so shared shell/layout,
 *   component reuse, spacing and palette application drift apart across pages.
 *
 *   The balance is a moderate cap. A small, related page cluster (family
 *   dashboard + courses + teachers) stays in ONE task so a single agent builds
 *   them with a cohesive visual language; only genuinely oversized tasks are
 *   chunked — and into domain-grouped chunks of MAX_VIEWS_PER_FRONTEND_TASK,
 *   never singletons.
 *
 *   404-safety is preserved by the planning-time page-coverage gate
 *   (gates/page-coverage-gate.ts + self-heal/page-coverage-repair.ts), which
 *   guarantees every PRD page is covered by *some* task — a grouped task
 *   counts, because the gate matches on coversRequirementIds / title /
 *   files.creates, not on a one-task-per-page rule.
 *
 * Split rules:
 *   - Only Frontend-phase tasks are considered.
 *   - A task with ≤ MAX_VIEWS_PER_FRONTEND_TASK view files is kept AS-IS.
 *   - A task with more is chunked into contiguous blocks of at most
 *     MAX_VIEWS_PER_FRONTEND_TASK, in the LLM's original file order (related
 *     pages are listed adjacently, so blocks stay cohesive and never collapse
 *     to needless singletons).
 *   - Non-view creates (tests, hooks) and modifies stay on the first chunk.
 *   - estimatedHours is divided evenly across chunks.
 *   - All other fields (dependencies, priority, coversRequirementIds,
 *     acceptanceCriteria, tddPlan) are copied to every chunk so no coverage
 *     metadata is lost.
 *   - After chunking, all task IDs and dependency references are re-sequenced
 *     T-001, T-002, … to restore a clean sequence.
 */

import type { KickoffWorkItem, TaskFilePlan } from "./types";

/**
 * Max view files a single Frontend task may own before it gets chunked.
 * This is the one tunable knob trading off 404-safety vs styling cohesion:
 *   - lower (→1) = safest against missing pages, weakest cross-page styling.
 *   - higher (≥5) = most cohesive, but risks an agent skipping pages → 404.
 * 3 keeps related page clusters together while staying small enough that one
 * agent reliably implements every page in the task.
 */
const MAX_VIEWS_PER_FRONTEND_TASK = 3;

export function splitMultiPageFrontendTasks(
  tasks: KickoffWorkItem[],
): KickoffWorkItem[] {
  const expanded: KickoffWorkItem[] = [];
  let didSplit = false;

  for (const task of tasks) {
    if (task.phase !== "Frontend") {
      expanded.push(task);
      continue;
    }

    const viewFiles = getViewFiles(task);
    // Keep cohesive clusters intact — a single agent builds them together so
    // layout, components, spacing and palette stay consistent across pages.
    if (viewFiles.length <= MAX_VIEWS_PER_FRONTEND_TASK) {
      expanded.push(task);
      continue;
    }

    // Oversized task — chunk into contiguous blocks (not singletons).
    didSplit = true;
    const chunks = chunkViewFiles(viewFiles, MAX_VIEWS_PER_FRONTEND_TASK);
    const creates = getCreates(task);
    const nonViewCreates = creates.filter((f) => !viewFiles.includes(f));
    const modifies = getModifies(task);
    const reads = getReads(task);
    const hoursEach = +(task.estimatedHours / chunks.length).toFixed(1);

    chunks.forEach((chunkViews, idx) => {
      const isFirst = idx === 0;

      expanded.push({
        ...task,
        // Temporary ID suffix — renumberTaskIds() will replace these.
        id: `${task.id}${String.fromCharCode(97 + idx)}`,
        title: `Implement ${deriveChunkLabel(chunkViews)}`,
        estimatedHours: hoursEach,
        files: {
          creates: isFirst ? [...chunkViews, ...nonViewCreates] : [...chunkViews],
          modifies: isFirst ? modifies : [],
          reads,
        },
        // tddPlan tests often reference multiple pages; keep on first chunk only
        // so the test file appears in its `files.creates`.
        tddPlan: isFirst ? task.tddPlan : undefined,
      });
    });

    console.info(
      `[split-multipage] "${task.id}" (${viewFiles.length} views) → ${chunks.length} tasks (${chunks.map(deriveChunkLabel).join(" | ")})`,
    );
  }

  if (!didSplit) return tasks;
  return renumberTaskIds(expanded);
}

// ─── helpers ─────────────────────────────────────────────────────────────────

function getCreates(t: KickoffWorkItem): string[] {
  if (!t.files) return [];
  if (Array.isArray(t.files)) return t.files;
  return (t.files as TaskFilePlan).creates ?? [];
}

function getModifies(t: KickoffWorkItem): string[] {
  if (!t.files || Array.isArray(t.files)) return [];
  return (t.files as TaskFilePlan).modifies ?? [];
}

function getReads(t: KickoffWorkItem): string[] {
  if (!t.files || Array.isArray(t.files)) return [];
  return (t.files as TaskFilePlan).reads ?? [];
}

function getViewFiles(t: KickoffWorkItem): string[] {
  return getCreates(t).filter((f) =>
    /^frontend\/src\/views\/[^/]+\.(tsx?|jsx?)$/.test(f),
  );
}

/** "frontend/src/views/FamilyProfilePage.tsx" → "Family Profile" */
function derivePageName(viewFilePath: string): string {
  const filename = viewFilePath.split("/").pop() ?? viewFilePath;
  const stem = filename.replace(/\.(tsx?|jsx?)$/, "").replace(/Page$/, "");
  return stem
    .replace(/([A-Z])/g, " $1")
    .trim()
    .replace(/^./, (c) => c.toUpperCase());
}

/**
 * Domain prefix = first CamelCase word of the view stem, used to keep related
 * pages together when chunking. "FamilyCoursesPage.tsx" → "Family",
 * "AdminUsersPage.tsx" → "Admin". Falls back to the whole stem when there is
 * no leading CamelCase word.
 */
function deriveDomain(viewFilePath: string): string {
  const filename = viewFilePath.split("/").pop() ?? viewFilePath;
  const stem = filename.replace(/\.(tsx?|jsx?)$/, "").replace(/Page$/, "");
  const m = stem.match(/^[A-Z][a-z0-9]+/);
  return m ? m[0] : stem;
}

/**
 * Slice view files into contiguous chunks of at most `max`, preserving order.
 * The LLM lists related pages adjacently, so in-order chunking keeps cohesive
 * neighbours together without ever producing needless singletons (which
 * domain-prefix grouping does when every page has a distinct prefix, e.g.
 * Private/Group/Lecture/Camp enrollment).
 */
function chunkViewFiles(viewFiles: string[], max: number): string[][] {
  const chunks: string[][] = [];
  for (let i = 0; i < viewFiles.length; i += max) {
    chunks.push(viewFiles.slice(i, i + max));
  }
  return chunks;
}

/**
 * Task-title label for a chunk. Single page → "Family Profile page"; a
 * same-domain cluster → "Family pages (Dashboard, Courses, Teachers)"; a mixed
 * chunk → the page names joined.
 */
function deriveChunkLabel(chunkViews: string[]): string {
  const names = chunkViews.map(derivePageName);
  if (names.length === 1) return `${names[0]} page`;

  const domain = deriveDomain(chunkViews[0]);
  const allSameDomain = chunkViews.every((f) => deriveDomain(f) === domain);
  if (allSameDomain) {
    const shortNames = names.map((n) =>
      n.startsWith(`${domain} `) ? n.slice(domain.length + 1) : n,
    );
    return `${domain} pages (${shortNames.join(", ")})`;
  }
  return `${names.join(", ")} pages`;
}

/**
 * Re-assign sequential IDs (T-001, T-002, …) and patch every
 * `dependencies[]` reference to match the new IDs.
 */
function renumberTaskIds(tasks: KickoffWorkItem[]): KickoffWorkItem[] {
  const oldToNew = new Map<string, string>();
  tasks.forEach((t, i) => {
    oldToNew.set(t.id, `T-${String(i + 1).padStart(3, "0")}`);
  });

  return tasks.map((t) => ({
    ...t,
    id: oldToNew.get(t.id) ?? t.id,
    dependencies: (t.dependencies ?? []).map((d) => oldToNew.get(d) ?? d),
  }));
}
