version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    networks:
      - dokploy-network
    restart: unless-stopped

networks:
  dokploy-network:
    external: true
